const { Task } = require('../models');

const taskdata = [
  {
    name: 'Dogwalker',
    description: 'i need someone to walk my dog, as i have broken my foot',
    startTime: 'April 21, 2022 09:00:00',
    endTime: 'April 21, 2022 13:00:00',
    taskCreator: 1,
    zip_code: "92082",
    status: false,
    username:"Sal",
  },
  {
    name: 'Mowing Lawn',
    description: 'I need someone to mow the lawn this week, as ill be out of town for the next month',
    startTime: 'April 21, 2022 07:00:00',
    endTime: 'April 21, 2022 08:00:00',
    taskCreator: 1,
    taskTaker: 2,
    zip_code: "92109",
    status: true,
    username:"Sal",
  },
  {
    name: 'Dishwashing',
    description: 'I have broken my hand and need someone to assist in washing dishes.',
    startTime: 'April 7, 2022 09:00:00',
    endTime: 'April 7, 2022 010:00:00',
    taskCreator: 5,
    taskTaker: 3,
    zip_code: "92109",
    status: true,
    username:"Jim",
  },
  {
    name: 'Transportation To Eye Doctor',
    description: 'I need to get my eyes checked and will be unable to see for a few hours. I am in need of a ride and assistance walking up my apartment stairs',
    startTime: 'April 9, 2022 11:00:00',
    endTime: 'April 9, 2022 13:00:00',
    taskCreator: 4,
    taskTaker: 5,
    zip_code: "92109",
    status: true,
    username:"Kelly",
  },
  {
    name: 'Light Bulb Changing',
    description: 'I would like for someone to come change my lightbulbs please, I have a ladder but am scared of heights.',
    startTime: 'April 1, 2022 11:00:00',
    endTime: 'April 1, 2022 12:00:00',
    taskCreator: 2,
    taskTaker: 3,
    zip_code: "92109",
    status: true,
    username:"Bob",
  },
  {
    name: 'Household Cleaning',
    description: 'I am moving and need a deep cleaning in order to get my deposit back',
    startTime: 'April 29, 2022 09:00:00',
    endTime: 'April 29, 2022 15:00:00',
    taskCreator: 8,
    taskTaker: 6,
    zip_code: "92109",
    status: true,
    username:"Jan",
  },
  {
    name: 'Gardening',
    description: 'I have broken my ankle and will not be able to water my beloved plants these next few weeks',
    startTime: 'April 2, 2022 08:00:00',
    endTime: 'April 2, 2022 9:00:00',
    taskCreator: 9,
    zip_code: "92109",
    status: false,
    username:"Peter",
  },
  {
    name: 'Cooking',
    description: 'i need someone to teach me some meal prep techniques.',
    startTime: 'April 9, 2022 08:00:00',
    endTime: 'April 9, 2022 9:00:00',
    taskCreator: 9,
    zip_code: "92109",
    status: false,
    username:"Peter",
  },
  {
    name: 'Painting',
    description: 'I need someone to help me paint my wall',
    startTime: 'March 29, 2022 13:00:00',
    endTime: 'March 29, 2022 15:00:00',
    taskCreator: 5,
    zip_code: "92109",
    status: false,
    username:"Jim",
  },
  {
    name: 'Cooking Lesson',
    description: 'I am making a big dinner and dont know how to cook, please help.',
    startTime: 'March 30, 2022 18:00:00',
    endTime: 'March 30, 2022 16:00:00',
    taskCreator: 6,
    zip_code: "92109",
    status: false,
    username:"Jill",
  },
  {
    name: 'Ride to Doctor',
    description: 'I have a doctors appointment that i need a ride for',
    startTime: 'March 31, 2022 8:00:00',
    endTime: 'March 31, 2022 11:00:00',
    taskCreator: 7,
    zip_code: "92109",
    status: false,
    username:"Meg",
  },
  {
    name: 'Bathroom Cleaning',
    description: 'I need some help cleaning the bathroom as i just had knee surgery.',
    startTime: 'April 1, 2022 8:00:00',
    endTime: 'April 1, 2022 9:00:00',
    taskCreator: 8,
    zip_code: "92109",
    status: false,
    username:"Jan",
  },
];

const seedTasks = () => Task.bulkCreate(taskdata);

module.exports = seedTasks;